### ISSUE TITLE
Support printing the documentation

### ISSUE THREAD

**Issue by SebastianNiemann** [Mantella/Mantella#330]
We should use `@media print` and `@media screen` inside our CSS file to provide a clean, paper optimised documentation, if printed.

For this, the navigation, header and footer should be removed. We may also need to unfold everything inside `<details>` and adjust some colours. However, it does not need to be black/white.

**Comment by pschiffmann** [comment]
Apparently we can't unfold the `details` tags for printing only: To do that, we need to set the `open` attribute of the tag to `true`, which can't be done with CSS, and JS events that only trigger before printing are not widely supported.
We now have the options to:
  * always fold the code examples, without a way to view them in printed documents
  * always unfold them, and the user has to close them by hand
  * unfold them by default, but add a _fold/unfold all_ button somewhere on the page
  * fold them by default, add a _print this page_ button to the page, and let when that button is clicked, open all details; users that use `ctrl-P` instead of our button still see the folded version

**Comment by pschiffmann** [comment]
Decided to go with "always fold the code examples, without a way to view them in printed documents" for now
