### ISSUE TITLE
Removing Armadillo dependencies from the CMA-ES pull request

### ISSUE THREAD

**Issue by SebastianNiemann** [Mantella/Mantella#355]

**Comment by SebastianNiemann** [comment]
@OpusV This issue still seems to be way to big. Maybe we should further split it into

- Analysing what of Armadillo needs to be re-implemented (matrix-matrix-multiplication, eigenvalues, ...)
- Replacing each of the identified function (one issue per function)

**Comment by SebastianNiemann** [comment]
@OpusV :point_left: **Poke**

**Comment by OpusV** [comment]
My proposal for issues in the order below:
- Analysing the required functions like matrix-matrix-multiplication or eigenvalues
- Implement each of them (single issue for every function)
- Test each of them (single issue for every function)
- Convert current version of CMA-ES to one without Armadillo (this will be the far biggest issue i guess)
- Write Tests for CMA-ES

...then push it to master...? 💃

**Comment by wlfbck** [comment]
As expected, both eigen calculations need a helper. Four other (yessish) functions should probably also get one, because of multiple use and somewhat long replacement code. symmatu is on the fence.

Arma Command | Datatype | in std or easily build
---------------- | ---------- | ---------------
arma::all		|	vec		|	yes
arma::min		|	vec		|	yes
arma::max		|	vec		|	yes
arma:ones		|	vec		|	yes
arma::abs		|	vec,mat	|	yes
arma::sum		|	mat		|	yes
arma::sort_index|	vec		|	yessish
arma::norm		|	vec		|	yes
arma::square	|	mat		|	yes
arma::sqrt		|	vec		|	yes
arma::sort		|	vec		|	yessish
arma::diagmat	|	vec		|	yes
arma::eig_gen	|	mat		|	no
arma::diagvec	|	mat		|	yessish
arma::accu		|	mat		|	yes
arma::symmatu	|	mat		|	yessish
arma::eig_sym	|	mat		|	no
arma::randu		|	mat		|	yes
arma::randn		|	mat		|	yes
arma::eye		|	mat		|	yes
arma::mean		|	vec		|	yes
arma::zeros		|	vec		|	yes
arma::normalise	|	vec		|	yes
